<?php
use \Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_form_alter().
 */
function clinic_database_integration_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_register_form' || $form_id == 'user_form'){
      $user = Drupal::service('current_user')->getRoles();
      $type = 'fieldset';
      if(!in_array("administrator", $user) && $form_id == 'user_form') {
          $type = 'hidden';
          $form['field_train_id']['#type'] = 'hidden';
      }

      $form['fpntc'] = array(
          '#type' => $type,
          '#title' => t('Clinic settings'),
          '#collapsible' => true,
          '#collapsed' => true,
          '#weight' => 2,
      );
      $form['fpntc']['field_train_id'] = $form['field_train_id'];
      unset($form['field_train_id']);
  }

}